-- CREATE TYPE MODAL_TYPES AS ENUM ('RODOVIARIO', 'FERROVIARIO', 'HIDROVIARIO', 'MARITIMO');
-- CREATE TYPE FLOW_TYPES AS ENUM ('RECEPCAO', 'EXPEDICAO');
-- CREATE TYPE MONTH_NAMES AS ENUM ('JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY',
--     'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER');

CREATE TABLE PROJECT
(
    ID          SERIAL PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR,

    CREATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT  TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT  TIMESTAMPTZ,


    CONSTRAINT PROJECT_NAME_UNIQUE UNIQUE (NAME)
);

CREATE TABLE SEASONALITY
(
    ID         SERIAL PRIMARY KEY,

    YEAR       INTEGER,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ

);
CREATE TABLE SEASONALITY_MONTH_DATA
(
    ID             SERIAL PRIMARY KEY,
    SEASONALITY_ID INTEGER REFERENCES SEASONALITY (ID),
    PERCENTAGE     DECIMAL,
    VALUE          DECIMAL,
    MONTH_NAME     VARCHAR(20),
    CREATED_AT     TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT     TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT     TIMESTAMPTZ,

    CONSTRAINT SEASONALITY_MONTH_DATA_MONTH_NAME_CHECK CHECK (MONTH_NAME in
                                                              ('JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE',
                                                               'JULY',
                                                               'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER'))

);
CREATE TABLE PRODUCT_CONFIG
(
    ID             SERIAL PRIMARY KEY,
    SEASONALITY_ID INTEGER REFERENCES SEASONALITY (ID),
    NAME           VARCHAR(255),

    CREATED_AT     TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT     TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT     TIMESTAMPTZ,

    CONSTRAINT PRODUCT_CONFIG_NAME_UNIQUE UNIQUE (NAME)
);
CREATE INDEX PRODUCT_CONFIG_NAME_INDEX ON PRODUCT_CONFIG (NAME);

CREATE TABLE PRODUCT
(
    ID             SERIAL PRIMARY KEY,
    SEASONALITY_ID INTEGER REFERENCES SEASONALITY (ID),
    PROJECT_ID     INTEGER REFERENCES PROJECT (ID),
    NAME           VARCHAR(100),
    VOLUME         DECIMAL,

    CREATED_AT     TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT     TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT     TIMESTAMPTZ,

    CONSTRAINT PRODUCT_NAME_UNIQUE UNIQUE (NAME)
);
CREATE INDEX PRODUCT_NAME_INDEX ON PRODUCT (NAME);


CREATE TABLE DIMENSION
(
    ID         SERIAL PRIMARY KEY,

    -- Review precision
    HEIGHT     DECIMAL,
    LENGTH     DECIMAL,
    WIDTH      DECIMAL,

    CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT TIMESTAMPTZ
);


CREATE TABLE TREM_TIPO
(
    ID                    SERIAL PRIMARY KEY,
    DIMENSION_ID          INTEGER REFERENCES DIMENSION (ID),
    NAME                  VARCHAR(100),
    VOLUME                DECIMAL,
    APPLICABLE_MODAL_TYPE VARCHAR(20),

    CREATED_AT            TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT            TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT            TIMESTAMPTZ,

    CONSTRAINT TREM_TIPO_NAME_UNIQUE UNIQUE (NAME),
    CONSTRAINT TREM_TIPO_APPLICABLE_MODAL_TYPE_CHECK CHECK (APPLICABLE_MODAL_TYPE in
                                                            ('RODOVIARIO', 'FERROVIARIO', 'HIDROVIARIO', 'MARITIMO'))
);
CREATE INDEX TREM_TIPO_NAME_UNIQUE_INDEX ON TREM_TIPO (NAME);
CREATE TABLE TRANSPORTER
(
    ID                    SERIAL PRIMARY KEY,
    NAME                  VARCHAR(100),
    VOLUME                DECIMAL,
    APPLICABLE_MODAL_TYPE VARCHAR(20),

    CREATED_AT            TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT            TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT            TIMESTAMPTZ,

    CONSTRAINT TRANSPORTER_NAME_UNIQUE UNIQUE (NAME),
    CONSTRAINT TRANSPORTER_APPLICABLE_MODAL_TYPE_CHECK CHECK (APPLICABLE_MODAL_TYPE in
                                                              ('RODOVIARIO', 'FERROVIARIO', 'HIDROVIARIO', 'MARITIMO'))
);

CREATE TABLE MODAL
(
    ID                 SERIAL PRIMARY KEY,
    SEASONALITY_ID     INTEGER REFERENCES SEASONALITY (ID),
    PRODUCT_ID         INTEGER REFERENCES PRODUCT (ID),
    TREM_TIPO_ID       INTEGER REFERENCES TREM_TIPO (ID),
    TRANSPORTER_ID     INTEGER REFERENCES TRANSPORTER (ID),
    TYPE               VARCHAR(20),
    CLASS_NAME         VARCHAR(100),
    FLOW_TYPE          VARCHAR(10),
    SHARE              DECIMAL,
    EXPEDICAO_CAPACITY DECIMAL,
    DAYS_BY_MONTH      INTEGER,
    OPERATIONAL_CYCLE  JSONB,

    CREATED_AT         TIMESTAMPTZ DEFAULT NOW(),
    UPDATED_AT         TIMESTAMPTZ DEFAULT NOW(),
    DELETED_AT         TIMESTAMPTZ,

    CONSTRAINT MODAL_TYPE_CHECK CHECK (TYPE in
                                       ('RODOVIARIO', 'FERROVIARIO', 'HIDROVIARIO', 'MARITIMO')),
    CONSTRAINT MODAL_FLOW_TYPE_CHECK CHECK (FLOW_TYPE in
                                            ('RECEPCAO', 'EXPEDICAO'))

);

CREATE TABLE APP_FEATURE_TOGGLE
(
    KEY        VARCHAR(30) PRIMARY KEY,
    VALUE      BOOLEAN     DEFAULT FALSE,

    UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);

