//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeniaWebApp.Resource {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLang_pt {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang_pt() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GeniaWebApp.Resource.AppLang_pt", typeof(AppLang_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string JANUARY {
            get {
                return ResourceManager.GetString("JANUARY", resourceCulture);
            }
        }
        
        internal static string changeLangConfirmation {
            get {
                return ResourceManager.GetString("changeLangConfirmation", resourceCulture);
            }
        }
        
        internal static string FEBRUARY {
            get {
                return ResourceManager.GetString("FEBRUARY", resourceCulture);
            }
        }
        
        internal static string MARCH {
            get {
                return ResourceManager.GetString("MARCH", resourceCulture);
            }
        }
        
        internal static string APRIL {
            get {
                return ResourceManager.GetString("APRIL", resourceCulture);
            }
        }
        
        internal static string MAY {
            get {
                return ResourceManager.GetString("MAY", resourceCulture);
            }
        }
        
        internal static string JUNE {
            get {
                return ResourceManager.GetString("JUNE", resourceCulture);
            }
        }
        
        internal static string JULY {
            get {
                return ResourceManager.GetString("JULY", resourceCulture);
            }
        }
        
        internal static string AUGUST {
            get {
                return ResourceManager.GetString("AUGUST", resourceCulture);
            }
        }
        
        internal static string SEPTEMBER {
            get {
                return ResourceManager.GetString("SEPTEMBER", resourceCulture);
            }
        }
        
        internal static string OCTOBER {
            get {
                return ResourceManager.GetString("OCTOBER", resourceCulture);
            }
        }
        
        internal static string NOVEMBER {
            get {
                return ResourceManager.GetString("NOVEMBER", resourceCulture);
            }
        }
        
        internal static string DECEMBER {
            get {
                return ResourceManager.GetString("DECEMBER", resourceCulture);
            }
        }
        
        internal static string portuguese {
            get {
                return ResourceManager.GetString("portuguese", resourceCulture);
            }
        }
        
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        internal static string languageChangeConsequences {
            get {
                return ResourceManager.GetString("languageChangeConsequences", resourceCulture);
            }
        }
        
        internal static string applyChanges {
            get {
                return ResourceManager.GetString("applyChanges", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        internal static string product_config_unique_name {
            get {
                return ResourceManager.GetString("product_config_unique_name", resourceCulture);
            }
        }
    }
}
